### ISSUE TITLE
Spitzer Image Program not displaying images properly

### ISSUE THREAD

**Issue by jaym878** [jaym878/SNR-Feasibility-Study#4]
Large FOV and non image displayed

**Comment by PaddyKavanagh** [comment]
James, can you send me the coordinates of the object that returned those images for the 3.6 micron filter so I can have a closer look.

**Comment by jaym878** [comment]
04h49m20s, -69d20m20s
I've also tested it with DEM L205 and got the same results at 3.6 and 8.0 microns

**Comment by PaddyKavanagh** [comment]
I think the problem might be the input coordinates. Are you converting them to decimal degrees before defining them in cell 2? The decimal degrees equivalent of the coordinates is:

test_src_coord = [72.3333, -69.3389]

If I run these I get reasonably sized images, e.g.,

![snr](https://user-images.githubusercontent.com/20085944/42047185-80d6223e-7af7-11e8-952a-66ecbe0f235c.png)

**Comment by jaym878** [comment]
I tried it with converted values earlier and it threw the same error. I think it could be how it’s handling the values so I’ll have a look and let you know
